spring:
  application:
    name: ${APPLICATION_NAME}
    security:
      jwt:
        secret-key: ${JWT_SECRET}
        expiration: ${JWT_EXPIRATION}
      name: ${APPLICATION_SECURITY_NAME}
      username: ${APPLICATION_SECURITY_USER}
      email: ${APPLICATION_SECURITY_EMAIL}
      password: ${APPLICATION_SECURITY_PASSWORD}
  mvc:
    static-path-pattern: classpath:/static/**
  redis:
    expiration: ${REDIS_EXPIRATION}
  profiles:
    active: dev
  jpa:
    open-in-view: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB