spring:
  application:
    name: ${APPLICATION_NAME}
    security:
      jwt:
        secret-key: ${JWT_SECRET}
        expiration: ${JWT_EXPIRATION}

      username: ${APPLICATION_SECURITY_USER}
      password: ${APPLICATION_SECURITY_PASSWORD}
  mvc:
    static-path-pattern: classpath:/static/**
  redis:
    expiration: ${REDIS_EXPIRATION}
  profiles:
    active: dev
  jpa:
    open-in-view: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
